### PR TITLE
account for schema in the append_select

### PR DESCRIPTION
**Pull request by llllllllll**

### CODE REVIEW

**Comment by llllllllll** [comment]
Sorry,I thought this had gone in, does this change look good to you because it is needed to make some of my app code work

**Comment by cpcloud** [comment]
yep this is fine

**Comment by cpcloud** [comment]
whoops

**Comment by cpcloud** [comment]
i'll merge this into master directly

**Comment by llllllllll** [comment]
kk, ty

**Comment by cpcloud** [comment]
done

**Pull request merged**
